### ISSUE TITLE
namelist description

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#11]
We need a full description of all the namelist files needed by CABLE:

 - cable.nml
 - pft_params.nml
 - cable_soilparms.nml

Some of that documentation can be found in JULES documentation in .rst format. Some online converter tools exist, for example, https://cloudconvert.com/rst-to-md 

This is part of #6

**Comment by tammasloughran** [comment]
The namelist files in the [namelist documentation](https://cable-lsm.github.io/CABLE/user_guide/inputs/cable_nml/) are always helpful for specific namelist variables. I can make tables for this with the default values and available values.

**Comment by tammasloughran** [comment]
@rkutteh, apparently you're working on this too? Have you made any progress on this? I didn't see any branch or pull request for this so I went ahead and made a branch. Do you agree on the columns?

**Comment by rkutteh** [comment]
@tammasloughran  I was in the process of populating the pft_params.nml and cable_soilparms.nml from the documentation on https://trac.nci.org.au/trac/cable/wiki/CableUserGuide/Configuration (some of which is obsolete). @ccarouge closed the pull request yesterday which is probably why you did not see the branch (deleted). I was about to start a new branch when I saw your message. Please feel free to go ahead with this as you would know more about the contents of the namelist files than me. Happy to review anything you make...

**Comment by tammasloughran** [comment]
Great, please continue. I will move on to the veg parameter file documentation.
