### ISSUE TITLE
Compilation of obsolete and deprecated code features 

### ISSUE THREAD

**Issue by rkutteh** [CABLE-LSM/CABLE#113]
@ccarouge @JhanSrbinovsky @gabsun I think it would be extremely useful to developers, documenters (I made this word up!), and even users, if we create a reference file where everyone involved in the project can include obsolete or deprecated features (e.g., settings) as they encounter them while contributing. This practice is of course standard in code development and programming textbooks (typically appearing at the end of the book). The file should contain at least two sections, one for **obsolete features** (as in features that were in use in past versions but have now been completely removed - usage results in an error,  and one for **deprecated features** (as in features scheduled for removal in the future - usage results in a warning). The file could go for example under CABLE/documentation/docs/developer_guide/
and should contain a brief description for each such feature and its reincarnation.

I think having such a file will bring code clean-up under more control as there seems to be quite a few of these features still floating around in the code.

**Comment by JhanSrbinovsky** [comment]
I agree they should be documented.

As well as the genuinely deprecated features, there are also features that are intended to be made available (such as GW) and also some are now implemented via another mechanism (yet the old code Is still “visible”).

Jhan
From: rkutteh ***@***.***>
Date: Monday, 9 January 2023 at 2:54 pm
To: CABLE-LSM/CABLE ***@***.***>
Cc: Srbinovsky, Jhan (Environment, Aspendale) ***@***.***>, Mention ***@***.***>
Subject: [CABLE-LSM/CABLE] Compilation of obsolete and deprecated code features (Issue #113)

@ccarouge<https://github.com/ccarouge> @JhanSrbinovsky<https://github.com/JhanSrbinovsky> @gabsun<https://github.com/gabsun> I think it would be extremely useful to developers, documenters (I made this word up!), and even users, if we create a reference file where everyone involved in the project can include obsolete or deprecated features (e.g., settings) as they encounter them while contributing. This practice is of course standard in code development and programming textbooks (typically appearing at the end of the book). The file should contain at least two sections, one for obsolete features (as in features that were in use in past versions but have now been completely removed - usage results in an error, and one for deprecated features (as in features scheduled for removal in the future - usage results in a warning). The file could go for example under CABLE/documentation/docs/developer_guide/
and should contain a brief description for each such feature and its reincarnation.

I think having such a file will bring code clean-up under more control as there seems to be quite a few of these features still floating around in the code.

**Comment by ccarouge** [comment]
Sure, go for it.
