### ISSUE TITLE
Input files description

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#12]
We need a description of all the input files (non-namelist):

 - [ ] gridinfo
 - [ ] restart
 - [X] met files

The description should include the expected units of the input data.

This is part of #6

**Comment by tammasloughran** [comment]
Also, the vegetation and soil parameter files should be added to that list

**Comment by tammasloughran** [comment]
I just realized this is old CABLE2.5 parameter file and is superseded by the new vegparams namelist files.

**Comment by tammasloughran** [comment]
I'm still confused. I thought that in CABLE3, the coding standards of the UM required that CABLE should not read it's own text files, and everything should be read from namelists. And yet in CABLE3 there is still the pftlookup parameters file that is read by casa_readbiome(). Are these ever going to be moved into the pft_params.mnl? or should the pftlookup table also be added to this list?

**Comment by ccarouge** [comment]
@tammasloughran we only update the CABLE code as it is added to JULES. Since we haven't yet started touching CASA, the CASA inputs are still the same as before and do not comply with the UM standards.

So the pftlookup table should be added to the list here.
