### ISSUE TITLE
Synchronise with SVN repository

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#155]
Before moving CABLE to GitHub, synchronise the source code under src/ with the trunk on SVN. This simplifies the merge on the day of the move.

**Comment by JhanSrbinovsky** [comment]
Huh? I hope you mean mods from documentation and not ACCESS3 stuff?

**Comment by ccarouge** [comment]
I mean make sure the source code is the same between SVN trunk and src/ in this repo under main. So that the `src/` directory already contains all the code changes that might have happened on trunk. It simplifies the merge on the day of the move, since `trunk` on SVN will become `main` here.
