### ISSUE TITLE
remove spurious oscillations in output with long run simulations

### ISSUE THREAD

**Issue by har917** [CABLE-LSM/CABLE#204]
Recent long run simulations using the NESP2.9_BLAZE branch have produced monthly time series output with alarming oscillations in the output of many variables (soil and litter carbon in particular) that appear only after a certain period of time (after 68 years hen lasting for 21 years).  The long run behaviour of the model appeared to not be affected.  

This symptom may also be responsible for separate work that raised concerns about the ability of CABLE3 to properly spin up.

Discussions within the community (@juergenknauer) indicate that this is not an issue with the science of the model, but rather because of a quirk with the triggering of output and that a fix exists in other branches.  Specifically replace
- lines 1570, 1584 and 1600 in [cable_output MAIN](https://github.com/CABLE-LSM/CABLE/blob/main/src/offline/cable_output.F90), with
- lines 1943, 1957 and 1972 in [cable_output POP_TRENDY](https://github.com/CABLE-LSM/CABLE/blob/CABLE-POP_TRENDY/offline/cable_output.F90)

Ultimately it appears that these symptoms are linked to numerics whereby the output triggering condition can be satisfied one time step too early/late, when `lastday+dday` gets large, without changing the averaging period.  Successive outputs then have one too few-one too many entries in the average and apparent oscillations appear.  The suggested change (in effect from an INT to a NINT) removes the symptom in tests considered - but the whole issue would appear to be somewhat non-resilient/twitchy which suggests that further work may be required for alternate use cases.

**Comment by juergenknauer** [comment]
Thanks for raising this issue, Ian. As mentioned above, I had issues with this and replacing INT with NINT solved it. 

There might be better/more resilient fixes to this problem.

**Comment by ccarouge** [comment]
This is now implemented in BLAZE_9184 which will get into CABLE-POP_TRENDY following the work to merge BIOS and POP_TRENDY. This is then considered done.
