### ISSUE TITLE
Adapt POP-TRENDY configuration to be run by anyone on CABLE4 project

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#208]
The POP-TRENDY script uses data that is not accessible to everyone. We need to:

- [X] copy the data to a common project, rp23
- [x] modify the POP-TRENDY script to use data from this project only
- [x] rewrite the R script to Python for creating the split land mask files
- [ ] manage the Python scripts in a package so it can be installed centrally and accessed by all.

**Comment by Whyborn** [comment]
I think we discuss the handling of scripts generally at the Land Team meeting on Wednesday and take the chosen path then, which I suspect will be adding a "CABLE_scripts" repository to the CABLE-LSM organisation.

**Comment by ccarouge** [comment]
This is now finished. The TRENDY configuration can be found here: https://github.com/CABLE-LSM/TRENDY_V12
