### ISSUE TITLE
review of CABLE's MPI implementation in various branches

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#209]
Need to fully understand why the MPI implementation in CABLE_POP-TRENDY performs so poorly. A first comparison with the implementation in the main branch does not reveal any major difference. A first hypothesis is POP-TRENDY is sending a lot more data across but we still need a definitive proof of this happening.

However, it is clear that CABLE generally sends a lot more data than necessary between the workers and the master processor. It seems it is sending all the global variables back to the master every timestep on the odd chance it is time to output the data. This is wasted communication time. It might be better to move the checks for output and any time averaging onto the workers.

Also, CABLE might be better off using a minimal MPI implementation and relying on parallel netcdf read/write instead.

**Comment by ccarouge** [comment]
@SeanBryan51 This is an old issue about MPI and I think we have somewhat passed this. Should we close/delete this and open another issue for the MPI work? Or do you feel there is work that is needed under this issue?

**Comment by SeanBryan51** [comment]
I'm happy to close this issue. https://github.com/CABLE-LSM/CABLE/issues/358 supersedes this.
