### ISSUE TITLE
Implement init_wetfac as per ACCESS3-JULES

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/CABLE#219]
As per discussions with @ccarouge this morning, the following issue in ACCESS3-JULES

https://github.com/CABLE-LSM/ACCESS3-JULES/issues/71

Should also occur in CABLE OFFLINE - particularly ensuring that init_wetfac implemented throughout the code.

Some notes from our discussion:

1. Bring init_wetfac into CABLE offline (here) - refactoring required
2. Test with benchcab
   - 5 site test (maybe 40) - confirm with Gab re lake sites
   - Run spatial tests
   - Bitwise comparison to ensure same results when switched off
   - Bitwise comparison to observe different results when switched on
   - Send to me.org for comparision

4. Once working in offline, bring the changes into ACCESS3-JULES

**Comment by JhanSrbinovsky** [comment]
hmmm - the changes are in ACCESS3-JULES, what do you mean by 3. ?

**Comment by bschroeter** [comment]
@JhanSrbinovsky - Sorry, there is a bit of detail missing here. Following discussions with Ian we're considering including a namelist switch to change which temperature is used (as per 71), but more comprehensively I've been asked to ensure that CABLE offline actually has the same functionality before implementing the switch in both repos.

**Comment by JhanSrbinovsky** [comment]
From memory Ben the only other thing to do other than the USE is add cbl_init_wetfac to the CMakeLists.txt file. Look in cbl_surf_wetness for what was "replaced" by call - was posted on #71

**Comment by JhanSrbinovsky** [comment]
[PR submitted to CABLE:main](https://github.com/CABLE-LSM/CABLE/pull/429/files?diff=split&w=1)
