### ISSUE TITLE
Use netcdf format for met forcings in NESP2pt9_BLAZE

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#233]
We want to adapt the TRENDY routines to read in the met forcing to accommodate for the BIOS input. The BIOS configuration has less variables that need to be read in.

The BIOS-specific reading code can be found by searching for 'bios' in [`offline/cable_driver.F90`](https://github.com/CABLE-LSM/CABLE/blob/NESP2pt9_BLAZE/offline/cable_driver.F90). Note that the MPI implementation requires looking at [`offline/cable_mpimaster.F90`](https://github.com/CABLE-LSM/CABLE/blob/NESP2pt9_BLAZE/offline/cable_mpimaster.F90) but it shouldn't be necessary in this step since it should use the same routines as the serial implementation to read in the inputs.

**Comment by Whyborn** [comment]
We're taking this issue to incorporate the two barriers between using the BIOS inputs on the TRENDY branch, which are
* The inputs for the BIOS branch are in binary format, but we want them in NetCDF.
* The BIOS inputs have fewer fields than the TRENDY inputs, so need different pre-processing before being passed to the weather generator.

**Comment by ccarouge** [comment]
@Whyborn This seems to be a duplicate of #322 which we have been using to communicate on this recently. OK to close?

**Comment by Whyborn** [comment]
Yep, ok to close I think @ccarouge
