### ISSUE TITLE
Compiling the MPI executable using the GNU compiler fails

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/CABLE#240]
Compiling the MPI executable for CABLE offline using the GNU compiler fails with the following error.

```
/home/189/sb8430/cable/src/offline/cable_mpiworker.F90:5686:49:

 5686 |                   //' (SUBROUTINE get_met_data)')
      |                                                 1
Error: Too many arguments in call to ‘abort’ at (1)
```

Steps to reproduce:

```
./build.bash --compiler gnu --mpi
```

The above command was run on commit: a6e0dccd19ee16158d64891979033f92d98197c5

**Comment by SeanBryan51** [comment]
The error lies inside the `worker_time_update` function:

https://github.com/CABLE-LSM/CABLE/blob/46830b3773f1932680af158cab27ae223fd8685a/src/offline/cable_mpiworker.F90#L5650-L5842

The function looks to be unused in the code base.

**Comment by ccarouge** [comment]
This is likely to change with the work to bring CABLE-POP_TRENDY in main and thus is deemed low priority

**Comment by SeanBryan51** [comment]
This patch fixes the issue:
```diff
diff --git a/src/offline/cable_mpiworker.F90 b/src/offline/cable_mpiworker.F90
index f240e55..bf5e64d 100644
--- a/src/offline/cable_mpiworker.F90
+++ b/src/offline/cable_mpiworker.F90
@@ -5655,6 +5655,7 @@ USE cbl_soil_snow_init_special_module

   SUBROUTINE worker_time_update (met, kend, dels)

+    USE cable_abort_module, ONLY: abort
     USE cable_common_module, ONLY: ktau_gl
     USE cable_def_types_mod
     USE cable_IO_vars_module
```

**Comment by SeanBryan51** [comment]
This was fixed in https://github.com/CABLE-LSM/CABLE/pull/410
