### ISSUE TITLE
Configurations for NESP2pt9_BLAZE

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#269]
We need to share testing configurations for the BIOS3 merge project. This issue is to discuss and document the status of these configurations.

We may also want to simplify the configuration we are going to use for the BIOS3 merge to make it simpler for any of us to pick it up.

# Status

Files are now available on Gadi under `/g/data/rp23/experiments/2024-04-17_BIOS3-merge/`

**Comment by ccarouge** [comment]
Information about the files:

• a directory for the underpinning 0.05 degree inputs
• copies of the inputs for the 3 main configurations that we run (0.25 degrees, 1000pts and ACT9)
• copies of the fotran and bash scripts to create those other configurations and a template bin_to_NetCDF program in the utilitities directory (pathnames will have to be updated for those to work!)
• BIOS3_runscripts contains run scripts which show how the files are used for the 3 main configurations
• gridinfo_inprogress was where I got up to with step A of the work plan (i.e. not very far).

**Comment by SeanBryan51** [comment]
I've added BIOS3_runscripts to GitHub: https://github.com/CABLE-LSM/BIOS3_runscripts

**Comment by SeanBryan51** [comment]
BLAZE_9184 branch: https://github.com/CABLE-LSM/CABLE/tree/BLAZE_9184

**Comment by SeanBryan51** [comment]
Here are my configuration changes for running the 1000 points configuration:

https://github.com/CABLE-LSM/BIOS3_runscripts/compare/main...sb8430%40gadi-configuration

**Comment by ccarouge** [comment]
We'll need to remove all references to `x45` and possibly `wd9`,is the data in `rp23`?

**Comment by SeanBryan51** [comment]
References to `x45` and `wd9`:

`/g/data/wd9/BenchMarking/CABLE-AUX_v20240122`
`/g/data/x45/Data_BLAZE`
`/g/data/x45/LUH2/v3h/*`
`/g/data/x45/CRUJRA2020/daily_1deg` (unused for BIOS)
`/g/data/x45/ipbes/masks/glob_ipsl_1x1.nc` (unused for BIOS)
`/g/data/x45/ipbes/masks/gridinfo_CSIRO_1x1.nc` (unused for BIOS)
`/g/data/x45/ipbes/${metmodel}/1deg` (unused for BIOS)
`/g/data/x45/ipbes/co2` (unused for BIOS)
`/g/data/x45/ipbes/ndep` (unused)

**Comment by har917** [comment]
@ccarouge @SeanBryan51 - I appreciate the enthusiasm to start on this.  However I/we need to update the git branches before too much more effort is undertaken.  There are a number of svn-era edits to carry across - impacting `/offline' directory '/core/biogeochem' directory and the run scripts.

One question - should I/we build into BLAZE_9184 or into NESP2pt9_BLAZE?  BLAZE_9184 was a development branch with the aim/aspiration that this would be short lived.

**Comment by SeanBryan51** [comment]
@har917 has updated the BIOS3 run scripts (`run_cable-pop.act9test.sh` and `run_cable-pop.1000pts.sh`) here: https://github.com/CABLE-LSM/CABLE/tree/BLAZE_9184/scripts

I have copied these over to the [BLAZE_9184_updates](https://github.com/CABLE-LSM/BIOS3_runscripts/tree/BLAZE_9184_updates) branch while I try to get these running.

**Comment by ccarouge** [comment]
@SeanBryan51 Something I forgot when discussing with you, it's absolutely fine to reduce the time period for the last step of the runs to 5 years. This would save some time. And once a configuration has run once, we will mostly want to run the last step only starting from restarts created before.

**Comment by SeanBryan51** [comment]
@har917 the following `act9test` run exceeds the allocated walltime (2 hours). PBS logs are attached below. What is the typical run time for the `act9test` case?

The run script I used is here: https://github.com/CABLE-LSM/BIOS3_runscripts/blob/BLAZE_9184_updates-sb8430%40gadi-configuration/run_cable-pop.act9test.sh. It should closely resemble your updated run script.

```
Started at Wed May 15 12:48:18 AEST 2024

Setup
    Serial / Parallel
        dompi=1
            nproc=4

    Sequence
        imeteo=0
        doextractsite=0
            experiment=ext_newblazempi_off
            randompoints=0
            latlon=42.536875,-72.172602
        doclimate=1
        dofromzero=1
        doequi1=1
            nequi1=4
        doequi2=1
            nequi2=4
        doiniluc=0
        doinidyn=1
        dofinal=1
        dofuture=0

    Options
        mettype=bios
        metmodel=hadgem2
        RCP=hist
        explicit_gm=0
        use_LUTgm=1
        Rubisco_params=Bernacchi_2002
        coordinate_photosyn=1
        coord=F
        acclimate_photosyn=1
        call_pop=1
        doc13o2=0
        c13o2_simple_disc=0

    Directories
        sitepath=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off
        cablehome=/home/189/sb8430/cable
        exe=/home/189/sb8430/cable/offline/cable-mpi
        aux=
        GlobalLandMaskFile=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/BIOS3_forcing/reccap1000pts/reccap1000pts
        SurfaceFile=/g/data/rp23/data/no_provenance/gridinfo/gridinfo_CSIRO_CRU05x05_4tiles.nc
        GlobalMetPath=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/BIOS3_forcing/reccap1000pts/met/
        GlobalTransitionFilePath=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/LUH2/v3h/0.25deg_aust/EXTRACT
        runpath=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off/run
        namelistpath=/scratch/tm70/sb8430/BIOStests/BLAZERuns/namelists_bios
        filename_veg=/scratch/tm70/sb8430/BIOStests/BLAZERuns/params_bios/def_veg_params.txt
        filename_soil=/scratch/tm70/sb8430/BIOStests/BLAZERuns/params_bios/def_soil_params.txt
        casafile_cnpbiome=/scratch/tm70/sb8430/BIOStests/BLAZERuns/params_bios/pftlookup.csv
        LandMaskFile=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off/mask/ext_newblazempi_off_landmask.nc
        MetPath=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off/met/bios_0.25deg
        ClimateFile=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off/mask/bios_climate_rst.nc
        TransitionFilePath=/scratch/tm70/sb8430/BIOStests/ext_newblazempi_off/LUH2/v3/1deg
        gm_lut_bernacchi_2002=/home/189/sb8430/cable/params/gm_LUT_351x3601x7_1pt8245_Bernacchi2002.nc
        gm_lut_walker_2013=/home/189/sb8430/cable/params/gm_LUT_351x3601x7_1pt8245_Walker2013.nc
        filename_d13c_atm=/home/189/sb8430/cable/params/graven_et_al_gmd_2017-table_s1-delta_13c-1700-2025.txt

1. Create climate restart file
=>> PBS: job killed: walltime 7206 exceeded limit 7200
======================================================================================
                  Resource Usage on 2024-05-15 14:48:36:
   Job Id:             115690070.gadi-pbs
   Project:            tm70
   Exit Status:        -29 (Job failed due to exceeding walltime)
   Service Units:      48.11
   NCPUs Requested:    4                      NCPUs Used: 4               
                                           CPU Time Used: 01:58:57        
   Memory Requested:   48.0GB                Memory Used: 2.3GB           
   Walltime requested: 02:00:00            Walltime Used: 02:00:17        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
```

**Comment by har917** [comment]
okay - it looks like you're trying to do a 1000 point run with only 4 processors (despite the file name).  That will take a fair bit of time end to end (more like 12-14 hours) given that you're doing all the steps.

If you look at the GlobalMetPath section in user=inh599 part - my run using this run script would be pointing to the ACT9 case.  This will (should) run through in around 20 minutes.  Your section points at the 1000pts data - so would need to be changed.

The alternate approach would be to go to 48 processors for this 1000 pt test (see the other script).

A lot of this comes down to the structure of the run script.  @AlisonBennett is using a somewhat simplified run script for her runs - see the .sh file in /scratch/x45/ab7412/CABLE_BIOS/AGCD_1000pts_sli_off/run/outputs/log  . In that we pull a lot of stuff out from the body of the script to co-locations near the top.

---------------------
*Note* - I have encountered problems with one of my recent ACT9 serial test runs.  This went really slowly (I had to split it up into two sections).  There's further details in the README in the x45/BLAZEruns_2024 directory.

**Comment by SeanBryan51** [comment]
@AlisonBennett can you put your simplified run script somewhere under `/scratch/public`? I'm running into permissions issues.

**Comment by SeanBryan51** [comment]
@AlisonBennett I can't seem to find your simplified run script, can you put the script somewhere under `/scratch/public`?

**Comment by har917** [comment]
@SeanBryan51 - apologies slight typo - that should have been /scratch/x45/ab7412/CABLE_BIOS/AGCD_1000pts_sli_off/run/logs/

The file is run_script_114838417.gadi-pbs.SC.sh

(At the moment) We're trying to keep run scripts co-located with the actual run output - this starting cause confusion/reproducibility issues.

**Comment by SeanBryan51** [comment]
I'm running into permissions issues when opening the run script:
```
$ cat /scratch/x45/ab7412/CABLE_BIOS/AGCD_1000pts_sli_off/run/logs/run_script_114838417.gadi-pbs.SC.sh
cat: /scratch/x45/ab7412/CABLE_BIOS/AGCD_1000pts_sli_off/run/logs/run_script_114838417.gadi-pbs.SC.sh: Permission denied
```

**Comment by ccarouge** [comment]
Copied to `/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ccc561/run_script_114838417.gadi-pbs.SC.sh`

**Comment by ccarouge** [comment]
We now have [existing configurations](https://github.com/CABLE-LSM/bios_testing/tree/main) we can work with so I'm closing this issue.
