### ISSUE TITLE
updating BLAZE_9184 branches with updates since branching from svn repository

### ISSUE THREAD

**Issue by har917** [CABLE-LSM/CABLE#272]
There are 3 areas of code development that should be brought into the BLAZE branch prior to efforts to merge capability with the CABLE-POP_TRENDY branch #232.  These are
- [x] a fix to address spurious oscillations in the output #204 
- [x] [fixes to BLAZE output](https://trac.nci.org.au/trac/cable/changeset?reponame=&new=9671%40branches%2FUsers%2Finh599%2FBLAZE_9184&old=9630%40branches%2FUsers%2Finh599%2FBLAZE_9184) (in BLAZE_9184 not in NESP2pt9_BLAZE)
- [x] fixes to POP dynamics carried across from [svn 9128](https://trac.nci.org.au/trac/cable/changeset/9218), [svn 9238](https://trac.nci.org.au/trac/cable/changeset/9238), [svn 9239](https://trac.nci.org.au/trac/cable/changeset/9239) and partner changes need to apply the same science capability using the standard MPI code.

In addition minor changes are needed to the BIOS run script to point to the updated (to end of 2023) binary meteorology files. 

**Update 29/04/24:**
All the additions have been made (including the scripts) but currently, the scripts return some errors that need to be investigated and fixed.

**Comment by har917** [comment]
@ccarouge since this intersects with other work, please advise on whether to build into the git BLAZE_9184 branch (and then git do the merge work into NESP2pt9_BLAZE), into NESP2pt9_BLAZE directly or both.

The code is ready to go in my `/home` area so this should be 'trivial' but I will undertake a small amount of testing once I've updated the git branches.

**Comment by har917** [comment]
@ccarouge How do I unlink the #237 pull request?

**Comment by har917** [comment]
[BLAZE_9184 branch](https://github.com/CABLE-LSM/CABLE/tree/BLAZE_9184) has been updated resolve this issue.

In addition two CABLE-POP run scripts (for the ACT9 test case and 1000pts test case) have been added into the scripts directory of the branch.  These will be useful for testing of merge of capability between BIOS and TRENDY branches.

**Comment by ccarouge** [comment]
> @ccarouge How do I unlink the https://github.com/CABLE-LSM/CABLE/pull/237 pull request?

Unlinked now: Righthand side menu -> Development. Click cog then repo that contains the PR, then click the checked PR to uncheck it, scroll down and click on Apply.

**Comment by ccarouge** [comment]
I've removed NESP2pt9_BLAZE from the title since the work was done in BLAZE_9184. It will get into NESP2pt9_BLAZE when we merge these 2 branches in a separate task.

**Comment by ccarouge** [comment]
I'm closing this issue since @har917 said everything was now done.
