### ISSUE TITLE
ESM1.5 reconciliation: casa_rplant

### ISSUE THREAD

**Issue by JhanSrbinovsky** [CABLE-LSM/CABLE#273]
Read only access to [TRAC ticket](https://trac.nci.org.au/trac/cable/ticket/362) raised by @rml599gh

**Comment by ccarouge** [comment]
This is a duplicate of #163 which had been transferred from the TRAC system. I prefer keeping the transferred issue rather than this one that links to TRAC (since TRAC might disappear at some point).
