### ISSUE TITLE
Test cases required for the BIOS3 merge work

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#276]
The BIOS3 work is mainly about I/O, so the tests should be designed to hit all the input cases. At the same time, the CABLE-POP_TRENDY branch does not have a working MPI implementation which makes testing on lots of points slow. Also, since BIOS uses input files tailored to the simulated domain, changing the domain means pre-processing the inputs for that domain.

Currently, the cases we have are:

- ACT 9 points: small and fast even on serial run but limited number of points
- "random" 1000 points: fast in parallel but pretty slow in serial. Should cover enough points to give a good code coverage.
- 0.25 degrees Australian configuration: covers the whole Australian continent but is expensive and slow to run even with MPI.

The question is whether the ACT case is enough to provide a test case for the work we need to do or not. Should we start with running a code coverage analysis between the ACT simulation and the 1000 points to see if there are parts of the code we do not hit that would matter for the I/O work?

**Comment by SeanBryan51** [comment]
I've created test cases for the `act9test` and `1000pts` configurations (see [bios_testing](https://github.com/CABLE-LSM/bios_testing) repository). I have generated code coverage reports for `act9test` and `1000pts` configurations and are attached below:

[bios_1000pts_coverage.tar.gz](https://github.com/user-attachments/files/15796532/bios_1000pts_coverage.tar.gz)
[bios_act9test_coverage.tar.gz](https://github.com/user-attachments/files/15796534/bios_act9test_coverage.tar.gz)

It looks like the `1000pts` has a slightly (~0.5%) larger coverage.

**Comment by ccarouge** [comment]
I've lost tracked. Is this done? Is the `act9test` test case short enough? Can it run in a serial run in a few minutes?

The code coverage results shared above show that they are almost identical. They differ in the biomes covered by each case but it confirms we can use the ACT9 case for standard testing.

**Comment by ccarouge** [comment]
I'm reorganising the issues on the configurations to reflect better what is happening on the BIOS work.

I'm closing this as done as we have checked that the ACT9 test case has a similar code coverage as the 1000 points case.
