### ISSUE TITLE
Units do not show up in user guide documentation

### ISSUE THREAD

**Issue by rkutteh** [CABLE-LSM/CABLE#298]
@ccarouge @SeanBryan51 
I noticed that units are not showing up in the user guide documentation. For example in https://cable.readthedocs.io/en/latest/user_guide/inputs/cable_soilparm_nml/   the units do not show up at all, whereas in https://github.com/CABLE-LSM/CABLE/blob/main/documentation/docs/user_guide/inputs/cable_soilparm_nml.md  they show up as syntax.

**Comment by rkutteh** [comment]
Hmm...I noticed that when I click on the link I included, they do show up, but I when I browse the page from the documentation link they do not show up.

**Comment by ccarouge** [comment]
Indeed. They seem to only appear after reloading the page.

**Comment by rkutteh** [comment]
On a related note (somehow), is it difficult to increase the width of the documentation pages, as they appear now unnecessarily narrow, with a lot of wasted white space on the sides. Wider pages would allow for viewing wider tables. Not sure if the setting is inside CABLE/documentation/docs/css/cable.css

**Comment by ccarouge** [comment]
I think it's possible to change the formatting of the site. I also want to deal with the formatting of the tables, the automatic column widths from markdown do not give the best result.
