### ISSUE TITLE
ncid_mask may not be correct for some applications - possible bug cable_input.F90

### ISSUE THREAD

**Issue by rml599gh** [CABLE-LSM/CABLE#306]
Trying to run CABLE offline for multiple sites with each set of site data in a single met data file.
Using the (x, y, t) format, the code tries to read a 'mask' or 'land' array at line 577 in cable_input.F90 but `ncid_mask` does not appear to be defined correctly. It is done for `ncciy > 0` but not in other cases.
Suggest adding 
`ncid_mask = ncid_met` immediately after line 485.

This seemed to solve the problem in my test case.

**Comment by JhanSrbinovsky** [comment]
can we just point this issue to the branch where you tested this and submit it as a Pull Request? Then we can    request a reviewer and merge it into main quickly

**Comment by rml599gh** [comment]
I will need help with this as I'm still not using git enough to remember things from one time to the next. I hadn't created a branch but have now managed that. Following the developers guide, I think I have done the 'add' and 'commit'. I have not managed to 'push' successfully. Maybe I still need to go through the set up for ACCESS-NRI stuff?

**Comment by JhanSrbinovsky** [comment]
If you have a branch created on GitHub and cloned locally, and comited your changes it is as simple as "git push" to push those local changes onto your branch at GitHub. So git has many two step processes compared to svn. Such as the add, commit one you just did. when you commit you do so to    your local clone of the repo. To push this to the global,remote,github version of the repo you have to do "git push". BTW git status will show you basically the same thing as svn status so try that as well. In general when you clone the repo in git you are making your own copy of the whole repo and in principle the new clone can enjoy a totally seperate life to what is available at git hub. git status will show you the status of your local clone. OTOH svn checkout was usually for a branch and when you committed it went straight back to the repo on TRAC
