### ISSUE TITLE
model-build-test-ci.yml failing

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#317]
@CodeGat, the build CI seems to be failing again.

You can see an example failed CI run here: https://github.com/CABLE-LSM/CABLE/actions/runs/9608988532 

It can't get the container from Docker:

```
  /usr/bin/docker --config /home/runner/work/_temp/.docker_1e0c0d80-271e-4427-8c9d-051ea785eef5 pull ghcr.io/access-nri/build-cable-intel2021.2.0-2024.06.21:latest
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.809 seconds before retry.
```

I have no idea if it's on the CI action side or on the CABLE side. It fails for all PRs.

**Comment by CodeGat** [comment]
@ccarouge would you be able to rerun the above failed workflow? That was 3 days ago when there was an issue with pushing images to our `ghcr.io/access-nri` container registry.

**Comment by ccarouge** [comment]
Will do. Just for info, this ran 12 hours ago and shows the same issue: https://github.com/CABLE-LSM/CABLE/actions/runs/9635318440

**Comment by ccarouge** [comment]
It seems to be working now, at least it seems to have found the Docker container: https://github.com/CABLE-LSM/CABLE/actions/runs/9608988532/job/26583782003

**Comment by ccarouge** [comment]
Thanks @CodeGat , I confirm the workflow ran through. I'll close this issue.

**Comment by ccarouge** [comment]
Sorry didn't realise I needed to put a comment to close the issue at the same time...
