### ISSUE TITLE
Unable to run BIOS configuration with POP on in CABLE-POP_TRENDY

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#321]
[ACT9_test](https://github.com/CABLE-LSM/BIOS3_runscripts/blob/act9test-CABLE-POP_TRENDY-port/run_cable-pop.act9test.sh) config runs on CABLE-POP_TRENDY. But this configuration only works with the LUC turned off.

We want to be able to run the full config of BIOS (latest stage) with LUC on.

**Comment by SeanBryan51** [comment]
Here is the act9 run script I used to run with CABLE-POP_TRENDY (with POP and POPLUC switched off): https://github.com/CABLE-LSM/BIOS3_runscripts/blob/act9test-CABLE-POP_TRENDY-port/run_cable-pop.act9test.sh

**Comment by ccarouge** [comment]
@AlisonBennett test with changing the namelist name to `cable_nml` in cable.nml file.

**Comment by AlisonBennett** [comment]
I have done the following tests:
1) Changing &cable to &cablenml at top of cable.nml file cable run failed at 'First spinup from zero biomass' due to LUC.nml now called luc.nml
2) Changed LUC.nml filename to luc.nml and references within runscript:

**Comment by ccarouge** [comment]
We need to look into. It seems TRENDY branch is expecting different variable names as BIOS. Probably use Lachlan's feature to add several possible names per variables.

**Comment by Whyborn** [comment]
I'll look into implementing this, or at least something similar.

**Comment by ccarouge** [comment]
Looking at a full diff of the HEADS of the two branches, it seems it is [only the latitude and longitude](https://github.com/CABLE-LSM/CABLE/compare/0521e809f285edd5116f2a194d8648013851feb9..5cf0d11ed9d44585b7171210487e285f6e948492#diff-7bd704b6a75304b80afd225eb17e9c731396680684b8ce280eca42c20f332343L190-L198) that have changed names.

**Comment by abhaasgoyal** [comment]
@AlisonBennett @ccarouge I am able to run BIOS config in `CABLE_POP-TRENDY` with LUC turned on (config is available as [act9test-CABLE-POP_TRENDY_LUC-port)](https://github.com/CABLE-LSM/BIOS3_runscripts/compare/act9test-CABLE-POP_TRENDY-port...act9test-CABLE-POP_TRENDY_LUC-port). I am assuming LUC is turned on by the following settings in the `act9test` script:
1. `cable_user%POPLUC = .TRUE.`
2. `call_pop=1`.

## Reproducibility steps
 
1. Generate 0.05° resolution gridinfo (`SurfaceFile`) by using @SeanBryan51 's [conversion script](https://gist.github.com/SeanBryan51/f89a30ee1e22495965dccb8fdff0f8c4#file-regrid_aus_05x05_to_005x005-sh) from the original 0.5° gridinfo ([gridinfo_CSIRO_CRU05x05_4tiles.nc](/g/data/rp23/data/no_provenance/gridinfo/gridinfo_CSIRO_CRU05x05_4tiles.nc)) and `--append-bios` option. The resulting gridinfo is named as [gridinfo_CSIRO_CRU005x005_4tiles.nc](`/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/data_005/gridinfo_CSIRO_CRU005x005_4tiles.nc).
2. Generate LUH2 inputs in 0.05° resolution (`GlobalTransitionFilePath`) with the necessary script [process_LUH2_TRENDY_new.sh](`/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/LUC-in-TRENDY/LUH2_processing/process_LUH2_TRENDY_new.sh`) by @juergenknauer with the following [BIOS grid config](/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/LUC-in-TRENDY/LUH2_processing/BIOS.grid.0pt05x0pt05deg) (parameters are referenced from `gridinfo_CSIRO_CRU005x005_4tiles.nc`):

```
gridtype  = lonlat
gridsize  = 544710
xsize     = 813
ysize     = 670
xname     = longitude
xlongname = "longitude"
xunits    = "degrees_east"
yname     = latitude
ylongname = "latitude"
yunits    = "degrees_north"
xfirst    = 112.95
xinc      = 0.05
yfirst    = -10.1
yinc      = 0.05
```
The resulting LUH2 files are stored in `/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/LUC-in-TRENDY/LUH2_inputs`

3. Defining namelist/parameter inputs and further changes before running config

Use namelists (v12) and soil/veg params from `CABLE_POP-TRENDY` and store them in [`BIOSTests/BlazeRuns`](/scratch/tm70/ag9761/BIOStests/BLAZERuns) . To make LUC namelist compatible with `CABLE_POP-TRENDY`, `NotPrimOnlyFile` was renamed to `PrimOnlyFile`. Note: Maybe we can a separate issue on this for [bios_testing#act9test](https://github.com/CABLE-LSM/bios_testing/tree/act9test) repository

Other changes such such changing `LUC.nml` to `luc.nml` were also done.

4. Run the configuration script in serial mode.

The results are available in `/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/LUC-in-TRENDY/ext_newblazempi_off` for further analysis. The PBS script itself gave the following output:

```
Started at Tue Sep 10 16:28:50 AEST 2024

Setup
    Serial / Parallel
        dompi=0
            nproc=1

    Sequence
        imeteo=0
        doextractsite=0
            experiment=ext_newblazempi_off
            randompoints=0
            latlon=42.536875,-72.172602
        doclimate=1
        dofromzero=1
        doequi1=1
            nequi1=4
        doequi2=1
            nequi2=4
        doiniluc=0
        doinidyn=1
        dofinal=1
        dofuture=0

    Options
        mettype=bios
        metmodel=hadgem2
        RCP=hist
        explicit_gm=0
        use_LUTgm=1
        Rubisco_params=Bernacchi_2002
        coordinate_photosyn=1
        coord=F
        acclimate_photosyn=1
        call_pop=1
        doc13o2=0
        c13o2_simple_disc=0

    Directories
        sitepath=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off
        cablehome=/home/659/ag9761/ACCESS-NRI/CABLE
        exe=/home/659/ag9761/ACCESS-NRI/CABLE/bin/cable
        aux=
        GlobalLandMaskFile=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/BIOS3_forcing/acttest9/acttest9
        SurfaceFile=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/data_005/gridinfo_CSIRO_CRU005x005_4tiles.nc
        GlobalMetPath=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/BIOS3_forcing/acttest9/met/
        GlobalTransitionFilePath=/g/data/rp23/experiments/2024-04-17_BIOS3-merge/ag9761/LUC-in-TRENDY/LUH2_inputs
        runpath=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off/run
        namelistpath=/scratch/tm70/ag9761/BIOStests/BLAZERuns/namelists_bios
        filename_veg=/scratch/tm70/ag9761/BIOStests/BLAZERuns/params_bios/def_veg_params.txt
        filename_soil=/scratch/tm70/ag9761/BIOStests/BLAZERuns/params_bios/def_soil_params.txt
        casafile_cnpbiome=/scratch/tm70/ag9761/BIOStests/BLAZERuns/params_bios/pftlookup.csv
        LandMaskFile=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off/mask/ext_newblazempi_off_landmask.nc
        MetPath=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off/met/bios_0.05deg
        ClimateFile=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off/mask/bios_climate_rst.nc
        TransitionFilePath=/scratch/tm70/ag9761/BIOStests/ext_newblazempi_off/LUH2/v3/1deg
        gm_lut_bernacchi_2002=/home/659/ag9761/ACCESS-NRI/CABLE/params/gm_LUT_351x3601x7_1pt8245_Bernacchi2002.nc
        gm_lut_walker_2013=/home/659/ag9761/ACCESS-NRI/CABLE/params/gm_LUT_351x3601x7_1pt8245_Walker2013.nc
        filename_d13c_atm=/home/659/ag9761/ACCESS-NRI/CABLE/params/graven_et_al_gmd_2017-table_s1-delta_13c-1700-2025.txt

1. Create climate restart file
2. First spinup from zero biomass
3. Bring biomass into quasi-equilibrium with restricted N and P pools
   3a. 30 year spinup from accumulated biomass; iequi1=1/4
   3b. Analytic solution of biomass pools
   3a. 30 year spinup from accumulated biomass; iequi1=2/4
   3b. Analytic solution of biomass pools
   3a. 30 year spinup from accumulated biomass; iequi1=3/4
   3b. Analytic solution of biomass pools
   3a. 30 year spinup from accumulated biomass; iequi1=4/4
   3b. Analytic solution of biomass pools
4. Bring biomass into quasi-equilibrium without restricted N and P pools
   4a. 30 year spinup from accumulated biomass; iequi2=1/4
   4b. Analytic solution of biomass pools
   4a. 30 year spinup from accumulated biomass; iequi2=2/4
   4b. Analytic solution of biomass pools
   4a. 30 year spinup from accumulated biomass; iequi2=3/4
   4b. Analytic solution of biomass pools
   4a. 30 year spinup from accumulated biomass; iequi2=4/4
   4b. Analytic solution of biomass pools
5b. Full dynamic spinup
6. Final centennial run

Finished at Tue Sep 10 16:54:30 AEST 2024   in 25.67 minutes.

======================================================================================
                  Resource Usage on 2024-09-10 16:54:34:
   Job Id:             124573291.gadi-pbs
   Project:            tm70
   Exit Status:        0
   Service Units:      10.29
   NCPUs Requested:    1                      NCPUs Used: 1               
                                           CPU Time Used: 00:25:35        
   Memory Requested:   48.0GB                Memory Used: 1.61GB          
   Walltime requested: 02:00:00            Walltime Used: 00:25:43        
   JobFS requested:    100.0MB                JobFS used: 0B              
======================================================================================
```


## Further steps

Now, I believe that creating 0.05° resolution with the updated script / using the new gridinfo solved the potential problem of expecting different name for longitude / latitude. @AlisonBennett @ccarouge  could you look into reproducing the results and seeing whether LUH2 provides the expected outputs.

**Comment by ccarouge** [comment]
> I believe that creating 0.05° resolution with the updated script / using the new gridinfo solved the potential problem of expecting different name for longitude / latitude.

I believe it's the reprocessing of the LUH2 data that solved this issue.

Thanks for the update.

**Comment by ccarouge** [comment]
@AlisonBennett to create some sanity check plots to ensure the run is not going weird.

**Comment by AlisonBennett** [comment]
I compared the output between a recent acttest9 run using the NESP2pt9 branch and AGCD forcing for some meteorology, main carbon pools and carbon fluxes.  
There are differences in the output.  These could arise from:
a) differences in the pre-1950 meteorology for Rainfall, Tair and Wind (the NESP2pt9 run used recycled met until 1951) 
b) differences in parameter files (the NESP2pt9 run used the pft_lookup for TRENDY v11)
c) LUC differences in the code
d) non-LUC differences in the code
e) other differences in the setup.

Overall, the results from this run seem to pass a sanity check, but there are too many differences in the runs to be certain that errors have not been introduced somewhere.

![annual_fluxes_ISSUE321_compare_NESP2pt9_acttest9____20241015_131151](https://github.com/user-attachments/assets/e206c4e9-a6c4-4b57-9644-8b850ba844b4)
![annual_fluxes_ISSUE321_compare_NESP2pt9_acttest9____20241015_131205](https://github.com/user-attachments/assets/067fe178-8916-44e7-be6e-e92890a9e3b1)
![Met_ISSUE321_compareNESP2pt9_acttest9____20241015_131103](https://github.com/user-attachments/assets/850d4c6f-1cd7-4e35-b042-a7c1f11b657d)
![Pools_tot__ISSUE321_compare_NESP2pt9_acttest9____20241015_131824](https://github.com/user-attachments/assets/a932df5e-932e-44bd-8ccf-8542cffc22d3)
![Pools_tot__ISSUE321_compare_NESP2pt9_acttest9____20241015_131847](https://github.com/user-attachments/assets/0d78bff2-604c-40f3-935f-92d5f74aff41)

**Comment by ccarouge** [comment]
The results from @AlisonBennett show the new run is different but has plausible results. We'll leave this issue to that, as it seems we can now run BIOS with POP on in CABLE-POP_TRENDY branch.
