### ISSUE TITLE
facilitate output of potential evaporation directly from the offline code base

### ISSUE THREAD

**Issue by har917** [CABLE-LSM/CABLE#335]
There are many applications where direct knowledge of potential evaporation (and/or its relation to simulated evaporation or evapotranspiration) would be of interest. However this is not facilitated by CABLE despite the `canopy%epot` variable carrying this information.  While an approximation of average potential evaporation could be estimated from other outputs, the nonlinearity in the equations implies that it would be better evaluated by CABLE's inbuilt time averaging.

Note that `ssnow%potev` in CABLE is more strictly the 'latent heat flux consistent with potential evaporation from the soil' not evaporation itself - i.e. units are currently W/m2 not mm of water/s - this may need to be handled within this issue.

**Comment by har917** [comment]
Process
- follow the general structure to add an additional output to offline model under flag out%potevap (check there maybe an existing entry)
- allocate output variable to `canopy%potev / air%rlam / ssnow%cls` (which is the conversion of the 'latent heat associated with potential evaporation to potential evpaoration'

**Comment by har917** [comment]
@ccarouge I may have been unlucky with exactly when you did a merge/update of MAIN - but benchcab seems to have failed for me.

I think the problem is that the cable.nml file that gets created is/was still back with 'check%range = .FALSE.' - with the net result that nothing runs (and the bitwise comparison fails)  - see
[cable.nml.txt](https://github.com/user-attachments/files/16243971/cable.nml.txt)

I also note that the site specific outputs seem to reference `ERROR ../../src/nccmp_state.c:156 No such file or directory` -e.g. 
[AU-ASM_2011-2017_OzFlux_Met_S0_R0_R1.txt](https://github.com/user-attachments/files/16243990/AU-ASM_2011-2017_OzFlux_Met_S0_R0_R1.txt) indicating that something else is missing.

Any suggestions? Perhaps I need to do a fresh git clone but I did do a benchcab clean all.

**Comment by har917** [comment]
> I think the problem is that the cable.nml file that gets created is/was still back with 'check%range = .FALSE.' 

I've checked - git status indicates that my local copy of benchcab is in sync with origin/main except for the config.yaml file, and the nml file attached is that created by benchcab (for AU-ASM). The out.txt file is giving the NAMELIST input error

**Comment by ccarouge** [comment]
@har917 I believe this is now solved or about to be solved from [the issue on benchcab repository](https://github.com/CABLE-LSM/benchcab/issues/302). We still need some changes to benchcab, spatial configurations and the benchcab documentation so it works for everyone but you should be good here.
