### ISSUE TITLE
Fix namelist incompatibility and some incompatibilities for GNU compiler in the new checks%range

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#344]
PR #287 has changed the type of the range%checks entry in the cable.nml namelist, but the corresponding change in the namelist with the source code was not implemented.

In addition, the code has introduced some IF statements on integer values that [will not compile with GNU compiler](https://gcc.gnu.org/onlinedocs/gfortran/Implicitly-convert-LOGICAL-and-INTEGER-values.html). These should be replaced with appropriate LOGICAL expressions.

Additionally, some non-standard line split symbols where introduced (\ instead of &).

**Comment by har917** [comment]
@ccarouge Apologies if over the top - could we also update the docs at line 130 of [meteorological_forcing.md](https://github.com/CABLE-LSM/CABLE/blob/e521096e4d6215b3d2f82b26f6fd249946096305/documentation/docs/user_guide/inputs/meteorological_forcing.md?plain=1#L130) and line 159 in [pft_params_nml.md](https://github.com/CABLE-LSM/CABLE/blob/e521096e4d6215b3d2f82b26f6fd249946096305/documentation/docs/user_guide/inputs/pft_params_nml.md?plain=1#L159) just to avoid confusion in the long run
