### ISSUE TITLE
Uninitialised variables in canopy routines (sum_rad_gradis, DvLitt)

### ISSUE THREAD

**Issue by rml599gh** [CABLE-LSM/CABLE#351]
`sum_rad_gradis` is calculated as `SUM(rad%gradis,2)`. It is first calculated in the `dryLeaf` subroutine (cbl_dryLeaf.F90, line 201) , then it is passed into `wetLeaf` (in cable_canopy.F90, line 405) and used there. Finally it is re-calculated and used in `cable_canopy` after `wetLeaf` (cable_canopy.F90, line 421).
However, it is not listed in the call to `dryLeaf` so appears to be unreliably passed back to canopy for use in `wetLeaf`. Offline testing seemed to show that this rarely crashed the model, even when compiled with Debug. Sometimes a floating point overflow error was generated. When it did run, repeated runs were not always reproducible.
One fix would be to recalculate `sum_rad_gradis` between the calls to `dryLeaf` and `wetLeaf`. Another option is to pass `rad%gradis` into `wetLeaf` and recalculate the sum there. This is what was done in CABLE2.4 era code.

**Comment by rml599gh** [comment]
Noting that sum_rad_rniso is also passed into wetLeaf but it is calculated in cable_canopy before dryLeaf, as well as being recalculated within dryLeaf. So this variable looks like it should be OK, but I haven't tested it.

**Comment by har917** [comment]
@ccarouge @JhanSrbinovsky This will need to come into AM3 at some point.

**Comment by ccarouge** [comment]
> edit: it looks like this has already been implemented in CABLE3 - with the dryLeaf value not being passed around and sum_rad_gradis recalculated inbetween dryLeaf and wetLeaf

Looking at the latest commit in main, the recalculation of `sum_rad_gradis` is after the call to wetLeaf.

Considering the current structure of the code:
https://github.com/CABLE-LSM/CABLE/blob/c2a54da6bfe0e2ddb0af164ad4c0ca00af521b5d/src/science/canopy/cable_canopy.F90#L392-L421

I would move the calculation of `sum_rad_gradis` together with `sum_rad_rniso`, above the initialisation of `rny`:
https://github.com/CABLE-LSM/CABLE/blob/c2a54da6bfe0e2ddb0af164ad4c0ca00af521b5d/src/science/canopy/cable_canopy.F90#L388-L392
 and pass it to `dryLeaf` and `wetLeaf`. I would replace all the `SUM(rad%gradis,2)`, `SUM(rad%rniso, 2)`, `SUM(rad%gradis(i,:))` and `SUM(rad%rniso(i,:))` with these variables in `define_canopy` and `cbl_dryLeaf` (there are too many cases to list them all here). `cbl_wetLeaf` is consistently using the calculated `sum_rad_rniso` and `sum_rad_gradis`

**Comment by rml599gh** [comment]
Claire- your suggestion sounds fine. Given we are bothering to define a `sum_rad_gradis` and `sum_rad_rniso`, we might as well use them consistently throughout.

**Comment by har917** [comment]
@ccarouge @rml599gh I suspect that the above would not be strictly bitwise reproducible.  Currently the first call to `wetLeaf()` is using an uninitialized value (so either 0, compiler value for uninitialized, or from previous time step/call) - this proposed rewrite would be using a 'proper' value

... but is that a concern?  This is attempting to fix a bug anyway (and as the element of `rad%` concerned are invariant through `define_canopy` and we iterate so it shouldn't matter)

**Comment by ccarouge** [comment]
Recently @SeanBryan51 noted that `canopy%DvLitt` is also uninitialised if the `cable_user%litter` option is false. I propose to expand this issue to add the initialisation of this variable. This variable isn't used when `cable_user%litter` is false, except it gets passed to subroutines within `REAL()` calls. Initialising this variable avoids error when running in debugging mode but will not change the scientific results.
