### ISSUE TITLE
Rewrite BIOS met to go through the new CRU routines

### ISSUE THREAD

**Issue by Whyborn** [CABLE-LSM/CABLE#391]
Want to make use of the new met input routines for the BIOS forcing (which use the AGCD dataset). Need to decouple the bits of BIOS initialisation that relate to the Met forcing and the bits that relate to BLAZE.

**Comment by Whyborn** [comment]
An extra difficulty here is that there is some branch logic relating to ```MetType == 'bios'``` in ```cable_weathergenerator.F90``` as well. I had not noticed this before, and makes things a bit more annoying to handle.

**Comment by ccarouge** [comment]
Closing this, working from #322
