### ISSUE TITLE
Support for `lat-lon` dimensions and coordinate variables in CABLE model output

### ISSUE THREAD

**Issue by SeanBryan51** [CABLE-LSM/CABLE#401]
As part of https://github.com/CABLE-LSM/CABLE/issues/210, ILAMB requires the spatial NetCDF dimensions and coordinate variables in the CABLE model output to be named `lat` and `lon` (or similar[^1]).

It looks like CABLE output files have been hard coded to be compatible with GrADS tool (uses `x` and `y` convention):

https://github.com/CABLE-LSM/CABLE/blob/0448257503a7a424807a6ee8daf3f1960faaf603/src/offline/cable_output.F90#L294-L302

https://github.com/CABLE-LSM/CABLE/blob/0448257503a7a424807a6ee8daf3f1960faaf603/src/offline/cable_output.F90#L402-L428

[^1]: the latitude/longitude dimension and coordinate variable must contain `lat`/`lon` as a substring in the dimension and coordinate variable name (see [here](https://github.com/CABLE-LSM/benchcab-ilamb-config/issues/1)).

**Comment by SeanBryan51** [comment]
I'm thinking we add a new optional field to the `output` namelist entry which allows the dimension and coordinate variable names to be configurable (with the default being the current GrADS names).

**Comment by aidanheerdegen** [comment]
See https://github.com/CABLE-LSM/benchcab-ilamb-config/issues/1#issuecomment-2354448846

**Comment by ccarouge** [comment]
GrADS is using the [COARDS convention](https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions). In this convention, the name of the coordinate variables is not standardized and normally a latitude or longitude coordinate is identifiable only on its unit. 

In other words, are we sure we have to keep the "x" and "y" options for compatibility?

**Comment by aidanheerdegen** [comment]
> GrADS is using the [COARDS convention](https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions). In this convention, the name of the coordinate variables is not standardized and normally a latitude or longitude coordinate is identifiable only by its unit.
> 
> In other words, are we sure we have to keep the "x" and "y" options for compatibility?

Longitude and latitude variable names are not standardised in the CF convention either. CF uses `units`, `standard_name` and `axis` attributes to identify lat/lon.

It seems CABLE has sufficient metadata to be CF compliant in this respect, it's just that Benchcab isn't implementing CF compliance currently.

**Comment by ccarouge** [comment]
@aidanheerdegen 
> Benchcab isn't implementing CF compliance currently

benchcab doesn't touch the output format, it only deals with the filenames. So if there is a problem, it's in the CABLE output format :)

**Comment by aidanheerdegen** [comment]
Sorry. When I said Benchab I meant iLAMB. Sorry.

**Comment by SeanBryan51** [comment]
Closing this issue for now - CABLE output currently has enough CF metadata to identify the spatiotemporal axis `(T, Z, Y, X)` of a given coordinate variable, so I agree with Aidan in that we should try and push ILAMB to accept CF compliant NetCDF data. If that falls over then we can consider changing the dimension names in the CABLE output.
