### ISSUE TITLE
Merge from AM3 - params 

### ISSUE THREAD

**Issue by JhanSrbinovsky** [CABLE-LSM/CABLE#402]
This issue covers the merging of code in params/ and utils/ directory from AM3 development. 

Null testing against offline will be required here @ccarouge, how do you want to proceed? I'm pretty sure I did this a month or so ago before moving on to the next part of the merge BUT: 
1.  I no longer have the output handy 
2. I still haven't used benchcab, I am still using manual pre-cursor to benchcab variety of testing.

Note: Not that it actually changes anything, but technically it does intersect with all applications of CABLE

[The overarching issue concerning AM3 merging is here](https://github.com/CABLE-LSM/CABLE/issues/403) #403

**Comment by ccarouge** [comment]
What is "null testing" ? Is that the same as regression testing?

**Comment by JhanSrbinovsky** [comment]
I just mean that the regression testing will/should show there is no difference, as expected
