### ISSUE TITLE
Investigate compiling science code as library

### ISSUE THREAD

**Issue by bschroeter** [CABLE-LSM/CABLE#441]
Following discussions with @ccarouge, we want to investigate whether the src/science code can be compiled as a library for use elsewhere.

On the face of it, there are a handful of commands to make this possible, assuming their are no cross-directory `USE` statements to contend with.

This is an exploratory exercise.

@ccarouge, please feel free to add additional context to this issue to guide my efforts.

**Comment by bschroeter** [comment]
Following exploratory efforts, there is a lot of cross-pollination (for lack of a better word) of source files across directories that call each other. In compiling just the "science" component of CABLE, all but 20 sources files of the entire repository are required to build a library.

Chances are, most of these will be orphaned `USE` statements, but it speaks to some structural issues where technical code (i.e. I/O) is called out of science, where it should be that science routines are isolated from technical code, accepting inputs and returning outputs (not opening files).

As per discussions with @ccarouge today - while structural changes are required, the priority is getting a library building with what we currently have. Here is what we are going to do to address this issue:

Copy everything that is currently interconnected in the offline directory over to a new ESM1.6 directory and build a library from that using spack.

Any future development in the ESM1.6 directories will obviously override these, but theoretically still be able to interface with the library itself.

@ccarouge, please elaborate if there is anything that I have misinterpreted.

**Comment by ccarouge** [comment]
Just a warning. When building the library like that, the compilation is likely to fall over when compiling with the UM because the copied files will be missing the ESM-specific modifications they need. Obviously this will be solved when integrating with Jhan's work.
