### ISSUE TITLE
Write a developer guide

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#7]
CABLE's developers need to establish a set of guidelines around CABLE's development in order to keep the code consistent and avoid duplications. 

We also need more documentation of the CABLE's source code to guide developers on the best way to integrate any new feature into the code base.

**Comment by aidanheerdegen** [comment]
See the forum discussion for details https://github.com/CABLE-LSM/CABLE/issues/7

**Comment by aidanheerdegen** [comment]
See the forum discussion for more information https://forum.access-hive.org.au/t/what-documentation-layout-should-we-use-for-cable/81

**Comment by myplaceholder** [comment]
test
