### ISSUE TITLE
Write documentation guidelines

### ISSUE THREAD

**Issue by ccarouge** [CABLE-LSM/CABLE#70]
Since the documentation is written collaboratively, we need some guidelines so that the end result looks like a coherent document.

**Comment by rkutteh** [comment]
I had a look and attached a pdf feedback. My main point there is that we should have a standard template that contributors can copy, paste at the top of each procedure, and populate. In this manner we ensure a uniform look to the inline documentation. 
I also separated the "arguments" description from the procedure header. Finally, I guess we should emphasize somewhere that the argument description specified implies a single argument or declaration per line.
   
[Guidelines for the scientific documentation.pdf](https://github.com/CABLE-LSM/CABLE/files/10061893/Guidelines.for.the.scientific.documentation.pdf)
